name: Generate README.md

on:
  push:
    branches: 
      - master
  workflow_dispatch:
  schedule:
  - cron: "0 0 */1 * *"

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
    - run: npm start
    - run: |
        git config user.name ZeegCL
        git config user.email hello.zeegcl@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[Octochef] Update this dish"
        git push origin master
